imports:
  - resource: config.yml

framework:
    trusted_hosts: '%trusted_hosts%'
    trusted_proxies: '%trusted_proxies%'

monolog:
    handlers:
        console:
            type: console
        main:
            action_level: error
            handler: nested
            type: fingers_crossed
        nested:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
