imports:
  - resource: config_dev.yml
  - resource: services_test.yml

parameters:
    api_url: http://api.elifesciences.org/
    api_mock: '%kernel.cache_dir%/guzzle/fixtures'

framework:
    profiler:
        collect: false
    session:
        storage_id: session.storage.mock_file
    test: ~

web_profiler:
    toolbar: false
