services:

    elife.guzzle.middleware.mock.storage:
        class: Csa\Bundle\GuzzleBundle\Cache\MockStorageAdapter
        arguments:
          - '%api_mock%'

    elife.guzzle.middleware.mock:
        class: Csa\Bundle\GuzzleBundle\GuzzleHttp\Middleware\MockMiddleware
        arguments:
          - '@elife.guzzle.middleware.mock.storage'
          - replay
        tags:
          - name: csa_guzzle.middleware
            alias: mock
            priority: -1250
