services:

    elife.api_sdk.client:
        class: eLife\ApiSdk\HttpClient\Guzzle6HttpClient
        arguments:
          - '@csa_guzzle.client.elife_api'

    elife.api_sdk.client.warning_checking:
        class: eLife\ApiSdk\HttpClient\WarningCheckingHttpClient
        decorates: elife.api_sdk.client
        arguments:
          - '@elife.api_sdk.client.warning_checking.inner'
          - '@logger'

    elife.api_sdk.labs:
        class: eLife\ApiSdk\ApiClient\LabsClient
        arguments:
          - '@elife.api_sdk.client'

    elife.api_sdk.subjects:
        class: eLife\ApiSdk\ApiClient\SubjectsClient
        arguments:
          - '@elife.api_sdk.client'

    elife.journal.templating.promise_aware:
        class: eLife\Journal\Templating\PromiseAwareEngine
        decorates: templating
        arguments:
          - '@elife.journal.templating.promise_aware.inner'

    elife.journal.twig.extension.info_bar:
        class: eLife\Journal\Twig\InfoBarExtension
        arguments:
          - '@elife.patterns.pattern_renderer'
        tags:
          - name: twig.extension

    elife.journal.twig.extension.pattern:
        class: eLife\Journal\Twig\PatternExtension
        arguments:
          - '@elife.patterns.pattern_renderer'
        tags:
          - name: twig.extension

    elife.journal.view_model.factory.footer:
        class: eLife\Journal\ViewModel\FooterFactory
        arguments:
          - '@elife.api_sdk.subjects'
          - '@router'
          - '@puli.url_generator'

    elife.journal.view_model.factory.site_header:
        class: eLife\Journal\ViewModel\SiteHeaderFactory
        arguments:
          - '@router'
          - '@puli.url_generator'

    elife.journal.view_model.factory.teaser_non_article_content:
        class: eLife\Journal\ViewModel\TeaserNonArticleContentFactory
        arguments:
          - '@router'
          - '@puli.url_generator'

    elife.patterns.pattern_renderer:
        class: eLife\Patterns\PatternRenderer\MustachePatternRenderer
        arguments:
          - '@mustache'

    elife.patterns.mustache.loader.puli:
        class: eLife\Patterns\Mustache\PuliLoader
        arguments:
          - '@puli.repository'

    elife.patterns.mustache.loader.filesystem:
        class: eLife\Patterns\Mustache\PatternLabLoader
        arguments:
          - '@=service("puli.repository").get("/elife/patterns/templates").getFilesystemPath()'
